// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaveApp.Infrastructure.Data;

#nullable disable

namespace WaveApp.Infrastructure.Migrations
{
    [DbContext(typeof(WaveDbContext))]
    [Migration("20261002012118_AddProductsk")]
    partial class AddProductsk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaveApp.Core.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("WaveApp.Core.Entities.PageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("WaveApp.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowBackorder")
                        .HasColumnType("boolean");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Category")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DimensionUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDigital")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WeightUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowBackorder = false,
                            Barcode = "100000000001",
                            Brand = "Wave",
                            Category = "Electronics",
                            Color = "Black",
                            CompareAtPrice = 179.99m,
                            CostPrice = 80.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Comfortable over-ear wireless headphones designed for music, meetings, travel, and everyday use.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Wireless+Headphones",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = true,
                            IsTaxable = true,
                            LowStockThreshold = 5,
                            MetaDescription = "Premium Wave wireless headphones with active noise cancellation.",
                            MetaTitle = "Wave Wireless Headphones",
                            Name = "Wave Wireless Headphones",
                            Price = 149.99m,
                            QuantityInStock = 45,
                            SKU = "WAVE-AUD-001",
                            ShortDescription = "Premium wireless headphones with active noise cancellation.",
                            Slug = "wave-wireless-headphones",
                            SubCategory = "Audio",
                            Tags = "headphones,audio,wireless,bluetooth",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Wireless+Headphones",
                            TrackInventory = true,
                            Weight = 0.35m,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            AllowBackorder = false,
                            Barcode = "100000000002",
                            Brand = "Wave",
                            Category = "Electronics",
                            Color = "Black",
                            CompareAtPrice = 139.99m,
                            CostPrice = 60.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Full-size mechanical keyboard with responsive switches and a durable professional design.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Mechanical+Keyboard",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = true,
                            IsTaxable = true,
                            LowStockThreshold = 5,
                            Name = "Wave Mechanical Keyboard",
                            Price = 119.99m,
                            QuantityInStock = 31,
                            SKU = "WAVE-CMP-002",
                            ShortDescription = "Mechanical keyboard designed for developers and professionals.",
                            Slug = "wave-mechanical-keyboard",
                            SubCategory = "Computer Accessories",
                            Tags = "keyboard,mechanical,computer,developer",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Mechanical+Keyboard",
                            TrackInventory = true,
                            Weight = 0.90m,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 3,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Electronics",
                            Color = "Graphite",
                            CostPrice = 24.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Precision wireless mouse designed for long work sessions and everyday productivity.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Ergonomic+Mouse",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = false,
                            IsTaxable = true,
                            LowStockThreshold = 10,
                            Name = "Wave Ergonomic Mouse",
                            Price = 49.99m,
                            QuantityInStock = 72,
                            SKU = "WAVE-CMP-003",
                            ShortDescription = "Comfortable wireless ergonomic mouse.",
                            Slug = "wave-ergonomic-mouse",
                            SubCategory = "Computer Accessories",
                            Tags = "mouse,wireless,computer,ergonomic",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Ergonomic+Mouse",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 4,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Electronics",
                            Color = "Black",
                            CompareAtPrice = 499.99m,
                            CostPrice = 290.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "A high-resolution 4K display suitable for software development, content creation, and office productivity.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=4K+Monitor",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = true,
                            IsTaxable = true,
                            LowStockThreshold = 4,
                            Name = "Wave 27-inch 4K Monitor",
                            Price = 449.99m,
                            QuantityInStock = 18,
                            SKU = "WAVE-DSP-004",
                            ShortDescription = "27-inch UHD monitor for productivity and development.",
                            Size = "27 inch",
                            Slug = "wave-27-inch-4k-monitor",
                            SubCategory = "Displays",
                            Tags = "monitor,4k,display,computer",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=4K+Monitor",
                            TrackInventory = true,
                            Weight = 5.2m,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 5,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Electronics",
                            Color = "Space Grey",
                            CostPrice = 69.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Connect displays, network, storage, and peripherals through a single USB-C connection.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=USB-C+Dock",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = false,
                            IsTaxable = true,
                            LowStockThreshold = 5,
                            Name = "Wave USB-C Docking Station",
                            Price = 129.99m,
                            QuantityInStock = 26,
                            SKU = "WAVE-CMP-005",
                            ShortDescription = "Multi-port USB-C docking station for modern workstations.",
                            Slug = "wave-usb-c-docking-station",
                            SubCategory = "Computer Accessories",
                            Tags = "usb-c,dock,laptop,computer",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=USB-C+Dock",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Accessories",
                            Color = "Black",
                            CompareAtPrice = 109.99m,
                            CostPrice = 42.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Durable backpack with padded laptop storage and compartments for cables, chargers, and accessories.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Developer+Backpack",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = true,
                            IsTaxable = true,
                            LowStockThreshold = 5,
                            Name = "Wave Developer Backpack",
                            Price = 89.99m,
                            QuantityInStock = 38,
                            SKU = "WAVE-BAG-006",
                            ShortDescription = "Professional laptop backpack for work and travel.",
                            Slug = "wave-developer-backpack",
                            SubCategory = "Bags",
                            Tags = "backpack,laptop,travel,developer",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Developer+Backpack",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 7,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Home",
                            Color = "Navy",
                            CostPrice = 12.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Reusable insulated mug designed to keep beverages hot or cold during work and travel.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Travel+Mug",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = false,
                            IsTaxable = true,
                            LowStockThreshold = 15,
                            Name = "Wave Insulated Travel Mug",
                            Price = 29.99m,
                            QuantityInStock = 95,
                            SKU = "WAVE-HOM-007",
                            ShortDescription = "Insulated stainless steel travel mug.",
                            Slug = "wave-insulated-travel-mug",
                            SubCategory = "Drinkware",
                            Tags = "mug,coffee,travel,drinkware",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Travel+Mug",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Clothing",
                            Color = "Navy",
                            CostPrice = 28.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Soft everyday hoodie designed for developers, engineers, and cloud enthusiasts.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Developer+Hoodie",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = true,
                            IsTaxable = true,
                            LowStockThreshold = 8,
                            Name = "Wave Developer Hoodie",
                            Price = 64.99m,
                            QuantityInStock = 55,
                            SKU = "WAVE-APP-008",
                            ShortDescription = "Comfortable Wave developer hoodie.",
                            Size = "L",
                            Slug = "wave-developer-hoodie",
                            SubCategory = "Hoodies",
                            Tags = "hoodie,developer,clothing,wave",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Developer+Hoodie",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 9,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Accessories",
                            Color = "Silver",
                            CostPrice = 25.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Ergonomic laptop stand designed to improve desk posture and workstation organization.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Laptop+Stand",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = false,
                            IsTaxable = true,
                            LowStockThreshold = 7,
                            Name = "Wave Laptop Stand",
                            Price = 54.99m,
                            QuantityInStock = 42,
                            SKU = "WAVE-CMP-009",
                            ShortDescription = "Adjustable aluminium laptop stand.",
                            Slug = "wave-laptop-stand",
                            SubCategory = "Office",
                            Tags = "laptop,stand,office,desk",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Laptop+Stand",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        },
                        new
                        {
                            Id = 10,
                            AllowBackorder = false,
                            Brand = "Wave",
                            Category = "Electronics",
                            Color = "Black",
                            CompareAtPrice = 159.99m,
                            CostPrice = 85.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CAD",
                            Description = "Fast portable storage for source code, documents, media, backups, and development environments.",
                            DimensionUnit = "cm",
                            ImageUrl = "https://placehold.co/800x600?text=Portable+SSD+1TB",
                            IsActive = true,
                            IsDigital = false,
                            IsFeatured = true,
                            IsTaxable = true,
                            LowStockThreshold = 5,
                            Name = "Wave Portable SSD 1TB",
                            Price = 139.99m,
                            QuantityInStock = 29,
                            SKU = "WAVE-STO-010",
                            ShortDescription = "Compact 1TB portable solid-state drive.",
                            Slug = "wave-portable-ssd-1tb",
                            SubCategory = "Storage",
                            Tags = "ssd,storage,portable,usb-c",
                            TaxRate = 13.00m,
                            ThumbnailUrl = "https://placehold.co/400x300?text=Portable+SSD+1TB",
                            TrackInventory = true,
                            WeightUnit = "kg"
                        });
                });

            modelBuilder.Entity("WaveApp.Core.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoginId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("WaveApp.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WaveApp.Core.Entities.Profile", b =>
                {
                    b.HasOne("WaveApp.Core.Entities.Login", "Login")
                        .WithOne("Profile")
                        .HasForeignKey("WaveApp.Core.Entities.Profile", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("WaveApp.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("WaveApp.Core.Entities.Login", "Login")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("WaveApp.Core.Entities.Login", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
